"""Verify stored contract copies, immediate editing, full snapshots and customer assignments."""
import argparse
import json
import re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://localhost:3001')
parser.add_argument('--output', default='docs/qa/contracts-clone')
args = parser.parse_args()
output = Path(args.output)
output.mkdir(parents=True, exist_ok=True)
checks, errors, writes = [], [], []

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, timezone_id='Asia/Ho_Chi_Minh', reduced_motion='reduce')
    page = context.new_page()
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.on('request', lambda request: writes.append(request.url) if '/api/' in request.url and request.method not in ['GET', 'HEAD'] else None)

    def navigate(label):
        if page.viewport_size['width'] < 600:
            page.get_by_role('button', name='Mở menu', exact=True).click()
            page.locator('.mg-mobile-nav').get_by_role('link', name=label, exact=True).click()
        else:
            page.locator('.mg-sidebar').get_by_role('link', name=label, exact=True).click()
        expect(page.locator('.mg-page-heading h1')).to_contain_text(label)
        page.locator('.mg-table tbody .mg-code').first.wait_for()

    def edit(code):
        page.get_by_role('button', name='Sửa ' + code, exact=True).click()
        form = page.locator('dialog.mg-contract-composer')
        expect(form).to_be_visible()
        return form

    page.goto(args.url + '/contracts', wait_until='networkidle')
    page.locator('.mg-table tbody .mg-code').first.wait_for()
    page.get_by_label('Lọc trạng thái', exact=True).select_option('cancelled')
    source_row = page.locator('.mg-table tbody tr').first
    source_code = source_row.locator('.mg-code').inner_text()
    source_cells = source_row.locator('td').all_inner_texts()[1:-1]
    original_customer = source_row.locator('.mg-identity strong').first.inner_text()
    page.get_by_role('button', name='Sao chép hợp đồng ' + source_code, exact=True).click()
    form = page.locator('dialog.mg-contract-composer')
    expect(form.get_by_role('heading', name='Chỉnh sửa hợp đồng')).to_be_visible()
    expect(form.locator('.mg-dialog-header')).to_contain_text('ID 33')
    expect(form.get_by_label('Số hợp đồng', exact=False)).to_have_value('HD-2610-033')
    expect(form.get_by_label('Số hợp đồng', exact=False)).to_have_attribute('readonly', '')
    expect(form.get_by_label('Trạng thái hợp đồng', exact=True)).to_have_value('cancelled')
    expect(form.get_by_label('Họ và tên', exact=True)).to_have_value(original_customer)
    expect(form.locator('.mg-lookup-status')).to_contain_text('Đã tìm thấy')
    expect(page.locator('.mg-title-count')).to_have_text('33')
    expect(page).to_have_url(args.url + '/contracts')
    expect(form.get_by_label('Nhân sự phụ trách', exact=False)).to_be_enabled()
    form.screenshot(path=str(output / 'clone-edit-1440.png'))
    checks.append('cancelled contract copy immediately creates ID/code 33, preserves cancellation/customer and opens edit without navigation')

    form.get_by_role('button', name='Lưu hợp đồng', exact=True).click()
    expect(form.locator('[aria-invalid="true"]')).not_to_have_count(0)
    staff = form.get_by_label('Nhân sự phụ trách', exact=False)
    active_id = staff.locator('option').evaluate_all('(options) => options.find(option => option.value && !option.disabled).value')
    staff.select_option(active_id)
    form.get_by_label('Thời gian bắt đầu', exact=False).fill('2026-10-10T09:15')
    form.get_by_label('Thời gian hẹn trả', exact=False).fill('2026-10-12T10:45')
    form.get_by_label('Họ và tên', exact=True).fill('Tên riêng của bản sao')
    form.get_by_label('Ghi chú hợp đồng', exact=True).fill('Tạo lại nhanh từ hợp đồng đã hủy')
    form.get_by_label('Trạng thái hợp đồng', exact=True).select_option('pending')
    form.get_by_label('Loại hợp đồng', exact=True).select_option('monthly')
    form.get_by_label('Tổng tiền thuê (VNĐ)', exact=True).fill('888000')
    form.get_by_label('Nguồn khách', exact=True).select_option('Nguyễn Minh An')
    form.get_by_role('button', name='Thêm xe vào mẫu', exact=True).click()
    vehicle0 = form.locator('#contract-vehicle-0').input_value()
    second = form.locator('#contract-vehicle-1')
    second_id = second.locator('option').evaluate_all('(options) => options.map(option => option.value).filter(Boolean)')
    second.select_option(next(value for value in second_id if value != vehicle0))
    form.locator('#contract-vehicle-1-color').fill('Màu riêng của xe thứ hai')
    form.locator('#contract-vehicle-1-driver_license_number').fill('GPLX-MAU-02')
    form.get_by_role('button', name='Lưu hợp đồng', exact=True).click()
    expect(form).not_to_be_visible()
    page.get_by_label('Lọc trạng thái', exact=True).select_option('')
    page.get_by_role('searchbox').fill('HD-2610-033')
    expect(page.locator('.mg-table tbody .mg-code')).to_have_text('HD-2610-033')
    expect(page.locator('.mg-table tbody')).to_contain_text('Chờ giao xe')
    expect(page.locator('.mg-table tbody')).to_contain_text('888.000')
    form = edit('HD-2610-033')
    for label, value in [('Họ và tên', 'Tên riêng của bản sao'), ('Ghi chú hợp đồng', 'Tạo lại nhanh từ hợp đồng đã hủy'), ('Nguồn khách', 'Nguyễn Minh An'), ('Tổng tiền thuê (VNĐ)', '888000')]:
        expect(form.get_by_label(label, exact=True)).to_have_value(value)
    expect(form.locator('.mg-composer-vehicle')).to_have_count(2)
    expect(form.locator('#contract-vehicle-1-color')).to_have_value('Màu riêng của xe thứ hai')
    expect(form.locator('#contract-vehicle-1-driver_license_number')).to_have_value('GPLX-MAU-02')
    page.wait_for_timeout(450)
    expect(form.get_by_label('Họ và tên', exact=True)).to_have_value('Tên riêng của bản sao')
    form.get_by_role('button', name='Xem mẫu in', exact=True).click()
    preview = page.locator('dialog.mg-contract-print-dialog')
    expect(preview).to_be_visible()
    expect(preview.locator('.contract-print-wrapper')).to_contain_text('Tên riêng của bản sao')
    expect(preview.locator('.contract-print-wrapper')).to_contain_text('HD-2610-033')
    preview.get_by_role('button', name='Quay lại thông tin', exact=True).click()
    form.get_by_role('button', name='Đóng', exact=True).click()
    page.get_by_role('searchbox').fill(source_code)
    expect(page.locator('.mg-table tbody tr')).to_have_count(1)
    assert page.locator('.mg-table tbody tr').locator('td').all_inner_texts()[1:-1] == source_cells
    checks.append('save/reopen retains custom customer, metadata, two vehicles and print data; original source remains unchanged')

    page.get_by_role('searchbox').fill('HD-2610-033')
    page.get_by_role('button', name='Sao chép hợp đồng HD-2610-033', exact=True).click()
    form = page.locator('dialog.mg-contract-composer')
    expect(form.get_by_label('Số hợp đồng', exact=False)).to_have_value('HD-2610-034')
    expect(form.get_by_label('Họ và tên', exact=True)).to_have_value('Tên riêng của bản sao')
    expect(form.locator('.mg-composer-vehicle')).to_have_count(2)
    expect(page.locator('.mg-title-count')).to_have_text('34')
    form.get_by_role('button', name='Đóng', exact=True).click()
    page.get_by_role('searchbox').fill('HD-2610-034')
    expect(page.locator('.mg-table tbody .mg-code')).to_have_text('HD-2610-034')
    checks.append('clone of an edited contract copies the full saved snapshot; closing edit keeps the already-created record')

    navigate('Khách hàng')
    page.get_by_role('button', name='Thêm khách hàng', exact=True).click()
    customer_form = page.get_by_role('dialog')
    customer_form.get_by_label('Họ và tên', exact=False).fill('Khách Blacklist mẫu')
    customer_form.get_by_label('Số điện thoại', exact=False).fill('0900001234')
    customer_form.get_by_label('Giấy tờ định danh', exact=True).fill('001234567890')
    customer_form.get_by_label('Cơ sở', exact=False).select_option('2')
    customer_form.get_by_label('Trạng thái hồ sơ', exact=False).select_option('blacklist')
    customer_form.get_by_role('button', name='Lưu dữ liệu mẫu', exact=True).click()
    expect(customer_form).not_to_be_visible()
    page.get_by_role('searchbox').fill('Khách Blacklist mẫu')
    expect(page.locator('.mg-table tbody .mg-status-red')).to_contain_text('Blacklist')
    page.get_by_label('Cơ sở đang xem', exact=False).select_option('2')
    expect(page.locator('.mg-table tbody .mg-code')).to_have_text('KH-033')
    page.get_by_label('Cơ sở đang xem', exact=False).select_option('1')
    expect(page.locator('.mg-table tbody')).to_contain_text('Không tìm thấy kết quả')
    page.get_by_label('Cơ sở đang xem', exact=False).select_option('2')
    page.get_by_role('button', name='Sửa KH-033', exact=True).click()
    customer_form = page.get_by_role('dialog')
    expect(customer_form.get_by_label('Cơ sở', exact=False)).to_have_value('2')
    expect(customer_form.get_by_label('Trạng thái hồ sơ', exact=False)).to_have_value('blacklist')
    customer_form.screenshot(path=str(output / 'customer-status-branch-1440.png'))
    customer_form.get_by_role('button', name='Hủy', exact=True).click()
    checks.append('new customers without contracts have persistent Blacklist and branch assignment, visible red status and direct branch filters')

    page.get_by_label('Cơ sở đang xem', exact=False).select_option('all')
    navigate('Cơ sở')
    page.get_by_role('button', name='Thêm cơ sở', exact=True).click()
    store_form = page.get_by_role('dialog')
    store_form.get_by_label('Tên cơ sở', exact=False).fill('Cơ sở bổ sung mẫu')
    store_form.get_by_label('Số điện thoại', exact=False).fill('0900001234')
    store_form.get_by_label('Người phụ trách', exact=False).fill('Quản lý mẫu')
    store_form.get_by_label('Địa chỉ', exact=False).fill('Địa chỉ cơ sở mẫu')
    store_form.get_by_role('button', name='Lưu dữ liệu mẫu', exact=True).click()
    navigate('Khách hàng')
    page.get_by_role('button', name='Thêm khách hàng', exact=True).click()
    customer_form = page.get_by_role('dialog')
    expect(customer_form.get_by_label('Cơ sở', exact=False).locator('option[value="5"]')).to_have_text('Cơ sở bổ sung mẫu')
    customer_form.get_by_role('button', name='Hủy', exact=True).click()
    checks.append('customer branch dropdown updates from the live shared branch catalog, including newly added branches')

    navigate('Danh sách hợp đồng')
    page.get_by_role('searchbox').fill('HD-2610-033')
    form = edit('HD-2610-033')
    form.get_by_label('CCCD / CMND', exact=False).fill('009876543210')
    expect(form.locator('.mg-lookup-status')).to_contain_text('Chưa có khách hàng')
    form.get_by_role('button', name='Thêm mới', exact=True).click()
    popup = page.get_by_role('dialog', name='Thêm khách hàng tại chỗ', exact=True)
    popup.get_by_label('Họ và tên', exact=False).fill('Khách popup Blacklist')
    popup.get_by_label('Số điện thoại', exact=False).fill('0900001234')
    popup.get_by_label('Địa chỉ', exact=False).fill('Địa chỉ mẫu popup')
    popup.get_by_label('Cơ sở', exact=False).select_option('3')
    popup.get_by_label('Trạng thái hồ sơ', exact=False).select_option('blacklist')
    popup.get_by_role('button', name='Lưu khách hàng mẫu', exact=True).click()
    expect(popup).not_to_be_visible()
    expect(form.get_by_label('Họ và tên', exact=True)).to_have_value('Khách popup Blacklist')
    expect(page).to_have_url(args.url + '/contracts')
    form.get_by_role('button', name='Đóng', exact=True).click()
    navigate('Khách hàng')
    page.get_by_role('searchbox').fill('Khách popup Blacklist')
    page.get_by_label('Cơ sở đang xem', exact=False).select_option('3')
    expect(page.locator('.mg-table tbody .mg-code')).to_have_text('KH-034')
    expect(page.locator('.mg-table tbody .mg-status-red')).to_contain_text('Blacklist')
    checks.append('inline customer popup also saves Blacklist and chosen branch without redirecting or silently discarding fields')

    page.get_by_label('Cơ sở đang xem', exact=False).select_option('all')
    navigate('Danh sách hợp đồng')
    page.set_viewport_size({'width': 375, 'height': 812})
    page.get_by_role('searchbox').fill('HD-2610-033')
    page.get_by_role('button', name='Sao chép hợp đồng HD-2610-033', exact=True).click()
    form = page.locator('dialog.mg-contract-composer')
    expect(form.get_by_label('Số hợp đồng', exact=False)).to_have_value('HD-2610-035')
    expect(form.get_by_label('Họ và tên', exact=True)).to_have_value('Tên riêng của bản sao')
    form.screenshot(path=str(output / 'clone-edit-375.png'))
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
    for _ in range(28):
        page.keyboard.press('Tab')
        assert page.evaluate('document.querySelector("dialog.mg-contract-composer").contains(document.activeElement)')
    page.keyboard.press('Escape')
    expect(form).not_to_be_visible()
    page.get_by_role('searchbox').fill('HD-2610-035')
    expect(page.locator('.mg-table tbody .mg-code')).to_have_text('HD-2610-035')
    page.screenshot(path=str(output / 'contracts-table-375.png'), full_page=True)
    checks.append('375px copy/edit keeps the stored record, traps keyboard focus, supports Escape and avoids page overflow')

    assert not errors, errors
    assert not writes, writes
    checks.append('no JavaScript errors and no rental/API mutations during any operation')
    browser.close()

result = {'passed': len(checks), 'checks': checks, 'page_errors': errors, 'api_writes': writes}
(output / 'functional-results.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
print(json.dumps(result, ensure_ascii=True, indent=2))
